url: "https://anderegg.ca"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:year/:month/:day/:title
author: "Gavin Anderegg"
title: "anderegg.ca"
description: "Something (slightly) less boring than nothing."
timezone: "America/Halifax"
logo: "/img/logo.png"
include: [".well-known"]
defaults:
  -
    scope:
      path: ""
    values:
      image: "/img/logo.png"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "wc2017/**/*"
    values:
      sitemap: false
