url: "https://anderegg.ca"
plugins:
  - jekyll-feed
  - jekyll-sitemap
permalink: /:year/:month/:day/:title
author: "Gavin Anderegg"
title: "anderegg.ca"
description: "Something (slightly) less boring than nothing."
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    scope:
      path: "wc2017/**/*"
    values:
      sitemap: false
